source 'https://github.com/CocoaPods/Specs.git'

target 'AOMultiproxier', :exclusive => true do
    pod "AOMultiproxier", :path => "../"
end

target 'Tests', :exclusive => true do
    pod "AOMultiproxier", :path => "../"
    
    pod 'Specta', '~> 0.2.1'
    pod 'Expecta'
    pod 'OCMock'
end